name: Deploy vsCode Extension
on:
  workflow_call:
    inputs:
      github_user:
        type: string
        required: true
      github_email:
        type: string
        required: true
    secrets:
      VSCE_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: phips28/gh-action-bump-version@v11.0.7
        with:
          skip-tag:  'false'
        env:
          GITHUB_USER: ${{ inputs.github_user }}
          GITHUB_EMAIL: ${{ inputs.github_email }}
      - run: npm install
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
